version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: daily
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: daily
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    groups:
      all-dependencies:
        patterns:
          - "*"
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
